import os
import re
from collections import defaultdict

schema = defaultdict(list)

# Read db structure from txt file
try:
    # the file was generated by mysql > db_structure.txt, might be utf-16 or latin1 or utf8
    with open('db_structure.txt', 'r', encoding='utf-16le') as f:
        lines = f.readlines()
        for line in lines:
            parts = line.strip().split('\t')
            if len(parts) >= 2:
                table_name = parts[0]
                col_name = parts[1]
                if table_name != 'TABLE_NAME' and table_name != 'table_name':
                    schema[table_name].append(col_name)
except Exception as e:
    try:
        with open('db_structure_utf8.txt', 'r', encoding='utf-8') as f:
            lines = f.readlines()
            for line in lines:
                parts = line.strip().split('\t')
                if len(parts) >= 2:
                    table_name = parts[0]
                    col_name = parts[1]
                    if table_name != 'TABLE_NAME' and table_name != 'table_name':
                        schema[table_name].append(col_name)
    except Exception as e2:
        print("Failed to read both txt files:", e2)
        import sys
        sys.exit(1)

print(f"Loaded {len(schema)} tables.")

# File extensions to search
valid_extensions = ['.php', '.js', '.tsx', '.ts', '.jsx', '.html']
search_dirs = [
    os.path.join("d:\\xampp\\htdocs\\Hadith", "api"),
    os.path.join("d:\\xampp\\htdocs\\Hadith", "spa")
]

file_paths = []
for d in search_dirs:
    for root, dirs, files in os.walk(d):
        if 'vendor' in root or 'node_modules' in root or '.git' in root or 'storage' in root or 'bootstrap' in root or 'public\\build' in root:
            continue
        for f in files:
            if any(f.endswith(ext) for ext in valid_extensions):
                file_paths.append(os.path.join(root, f))

print(f"Searching {len(file_paths)} files...")

def escape_regex(s):
    return re.escape(s)

results = {}

for table, columns in schema.items():
    table_usages = []
    col_usages = {col: [] for col in columns}
    
    table_pattern = re.compile(r'\b' + escape_regex(table) + r'\b', re.IGNORECASE)
    col_patterns = {col: re.compile(r'\b' + escape_regex(col) + r'\b', re.IGNORECASE) for col in columns}
    
    for fp in file_paths:
        try:
            with open(fp, 'r', encoding='utf-8') as f:
                lines = f.readlines()
        except:
            continue
            
        for i, line in enumerate(lines):
            line_num = i + 1
            rel_path = os.path.relpath(fp, "d:\\xampp\\htdocs\\Hadith").replace('\\', '/')
            
            if table_pattern.search(line):
                table_usages.append(f"{rel_path}:{line_num}")
                
            for col, pattern in col_patterns.items():
                if pattern.search(line):
                    col_usages[col].append(f"{rel_path}:{line_num}")
                    
    results[table] = {
        'table_usages': table_usages,
        'col_usages': col_usages
    }

# Generate markdown
md_path = "C:\\Users\\elgar\\.gemini\\antigravity-ide\\brain\\cf4721fb-7813-4fd1-abc1-62a08a063073\\db_usage_report.md"
with open(md_path, 'w', encoding='utf-8') as f:
    f.write("# Database Usage Report\n\n")
    f.write("This report lists every table and column in the database, mapping them to file locations where they are used.\n\n")
    
    for table, data in results.items():
        table_usages = data['table_usages']
        col_usages = data['col_usages']
        
        f.write(f"## Table: `{table}`\n")
        
        if table_usages:
            f.write(f"**Used in ({len(table_usages)} places):**\n")
            # Limit to 5 for brevity
            for u in table_usages[:5]:
                f.write(f"- {u}\n")
            if len(table_usages) > 5:
                f.write(f"- ... and {len(table_usages) - 5} more\n")
        else:
            f.write("**Status: Possibly Unused (Table name not found in code)**\n")
            
        f.write("\n### Fields\n")
        f.write("| Field | Type/Usage | Status |\n")
        f.write("|---|---|---|\n")
        
        for col, usages in col_usages.items():
            if usages:
                usage_str = ", ".join(usages[:3])
                if len(usages) > 3:
                    usage_str += f" (+{len(usages)-3} more)"
                f.write(f"| `{col}` | {usage_str} | Used |\n")
            else:
                f.write(f"| `{col}` | N/A | **Possibly Unused** |\n")
                
        f.write("\n---\n")

print("Done generating report.")
